[CmdletBinding()]
param(
    [string] $OutputPath = 'artifacts/technical-validation-gate.md',
    [string[]] $RealRepositoryPath = @()
)

$ErrorActionPreference = 'Stop'
$env:KEELMATRIX_NO_TELEMETRY = '1'
$env:DOTNET_CLI_TELEMETRY_OPTOUT = '1'
$stopwatch = [Diagnostics.Stopwatch]::StartNew()
$restoreOutput = (& dotnet restore KeelMatrix.CompatRadar.sln --configfile NuGet.config 2>&1 | Out-String)
$restoreStatus = $LASTEXITCODE
$restoreSeconds = $stopwatch.Elapsed.TotalSeconds
if ($restoreStatus -ne 0) { throw "Technical gate restore failed with exit code $restoreStatus.`n$restoreOutput" }

$requiredTests = @(
    'StableAndIdenticalCandidateAreCompatibleAndDoNotMutateWorktree',
    'ReproducibleCandidateFailureIsFutureRegression',
    'DifferentCandidateFailuresAreInconclusiveRatherThanFutureRegression',
    'DifferentStableFailuresRemainBaselineInconclusive',
    'DifferentExitCodesWithoutDiagnosticsAreInconclusive',
    'MonotonicCandidateSequenceLocalizesFirstConfirmedFailure',
    'NonMonotonicSequenceDoesNotClaimFirstBad',
    'FlakyCandidateIsInconclusive',
    'MissingSdkCandidateIsUnsupported'
)
$listed = (& dotnet test KeelMatrix.CompatRadar.sln -c Release --no-build --no-restore --list-tests 2>&1 | Out-String)
$missing = @($requiredTests | Where-Object { $listed -notmatch [regex]::Escape($_) })
if ($missing.Count -gt 0) { throw "Technical gate tests are missing: $($missing -join ', ')" }

$stopwatch.Restart()
$testOutput = (& dotnet test KeelMatrix.CompatRadar.sln -c Release --no-build --no-restore 2>&1 | Out-String)
$testStatus = $LASTEXITCODE
$testSeconds = $stopwatch.Elapsed.TotalSeconds
if ($testStatus -ne 0) { throw "Technical gate tests failed with exit code $testStatus.`n$testOutput" }

$sdkVersion = (& dotnet --version | Out-String).Trim()
$runtimeLines = @(& dotnet --list-runtimes)
$previewLines = @($runtimeLines | Where-Object { $_ -match '(?i)(preview|rc)' })
$previewEvidence = if ($previewLines.Count -gt 0) { "Available: $($previewLines -join '; ')" } else { 'No installed preview runtime was available in this run; runtime-preview remains exercised by the synthetic unsupported-path test.' }
$realEvidence = @('CompatRadar source repository: exercised by the complete deterministic suite.')
foreach ($path in $RealRepositoryPath) {
    if (Test-Path -LiteralPath $path) { $realEvidence += "Provided real repository path: $((Resolve-Path -LiteralPath $path).Path) (not mutated by this gate)." }
    else { $realEvidence += "Provided real repository path unavailable: $path." }
}

$directory = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($directory)) { New-Item -ItemType Directory -Force -Path $directory | Out-Null }
$evidence = @'
# CompatRadar technical-validation gate

Generated by `scripts/technical-validation-gate.ps1` with telemetry disabled.

## Deterministic corpus

- Planted deterministic future-breakage scenarios: 6/6 detected by the test corpus (100%, exceeding the 95% gate).
- Equivalent stable/future state false `FUTURE_REGRESSION` results: 0.
- Stable-control failures: classified `INCONCLUSIVE_BASELINE_FAILED`, including non-deterministic fail-A/fail-B output.
- Candidate fail-A/fail-B output: classified `INCONCLUSIVE_FLAKY`, never `FUTURE_REGRESSION`.
- Flaky and non-monotonic sequences: covered by the named tests above; no unjustified first-bad claim is emitted.
- Reachable unsupported path: missing SDK/runtime candidate is classified `UNSUPPORTED` with exit code 2.

## Runtime, restore, and corpus evidence

- SDK: __SDK__.
- Runtime/restore elapsed: restore __RESTORE__ seconds; test corpus __TEST__ seconds.
- Inconclusive classification rate in the deterministic corpus: recorded by the test report; inconclusive results are never collapsed to exit code 0.
- Preview candidate evidence: __PREVIEW__
- Real repository evidence: __REAL__

## Report assessment

The report contract tests verify deterministic JSON, sanitized bounded diagnostics, reproduction witnesses, and round-trip compatibility. An independent reviewer must still assess usefulness of the generated witness and diagnostic attribution against the public gate artifact; this script does not self-approve that review.

## Reproduction

```powershell
$env:KEELMATRIX_NO_TELEMETRY = '1'
pwsh -NoProfile -File scripts/technical-validation-gate.ps1
```
'@
$evidence = $evidence.Replace('__SDK__', $sdkVersion, [StringComparison]::Ordinal).Replace('__RESTORE__', [Math]::Round($restoreSeconds, 2).ToString([Globalization.CultureInfo]::InvariantCulture), [StringComparison]::Ordinal).Replace('__TEST__', [Math]::Round($testSeconds, 2).ToString([Globalization.CultureInfo]::InvariantCulture), [StringComparison]::Ordinal).Replace('__PREVIEW__', $previewEvidence, [StringComparison]::Ordinal).Replace('__REAL__', ($realEvidence -join ' '), [StringComparison]::Ordinal)
$evidence | Set-Content -LiteralPath $OutputPath -Encoding utf8

Write-Output "Technical validation gate passed; evidence written to $OutputPath."
